create database teste;

drop database teste;

use teste;

# DEFININDO COLUNAS
# COLUNA DATATYPE CONSTRAINT

# TIPO DE DADOS
# CHAR(SIZE): UMA STRING DE TAMANHO FIXO DE 0 A 255 CARACTERES | PODE TER LETRAS NÚMEROS CARACTERES ESPECIAIS | DEFAULT É 1
# VARCHAR(SIZE): UMA STRING DE TAMANHO VARIADO DE 0 A 65535 CARACTERES | PODE TER LETRAS NÚMEROS CARACTERES ESPECIAIS
# ENUM(VALUE1, VALUE2, ...): UM OBJETO DE STRING QUE SÓ PODE TER UM VALOR A PARTIR DE UMA LISTA DE POSSIBILIDADES | RECEBE UM ESPEÇO EM BRANCO SE FOR INSERIDO UM VALOR INVÁLIDO
# SET(VALUE1, VALUE2, ...): UM OBJETO DE STRING QUE PODE TER 0 OU MAIS VALORES A PARTIR DE UMA LISTA DE POSSIBILIDADES | POSSO LISTAR ATÉ 64 VALORES
# BOOL OU BOOLEAN: 0 É FALSO E QUALQUER OUTRO VALOR É VERDADEIRO
# INTEGER(SIZE) OU INT(SIZE): VALORES INTEIROS NO QUAL O SIZE ESPECIFICA O TAMANHO MÁXIMO | UNISIGNED INT CONSEGUE UM LIMITE MAIOR DE INTEIROS POSITIVOS
# FLOAT(SIZE, D): SIZE É O NÚMERO TOTAL DE DÍGITOS E D SÃO OS NÚMEROS APÓS A VÍRGULA (PONTO DECIMAL) | FOI DESCONTINUADO 
# DOUBLE(SIZE, D): SIZE É O NÚMERO TOTAL DE DÍGITOS E D SÃO OS NÚMEROS APÓS A VÍRGULA (PONTO DECIMAL)
# DEC(SIZE, D) OU DECIMAL(SIZE, D): SIZE É O NÚMERO TOTAL DE DÍGITOS E D SÃO OS NÚMEROS APÓS A VÍRGULA (PONTO DECIMAL) | PRECISÃO EXATA DE VALORES | NÚMERO EXATO DE PONTO FIXO (NÚMMERO DEPOIS DA VÍRGULA FIXO)

# CONSTRAINTS (RESTRIÇÕES)
# NOT NULL: GARANTE QUE UMA COLUNA NÃO ASSUMA VALOR NULO
# UNIQUE: GARANTE QUE TODOS OS VALORES EM UMA COLUNA SÃO DIFERENTES
# PRIMARY KEY: UMA COMBINAÇÃO DE NOT NULL E UNIQUE (IDENTIFICA UNICAMENTE CADA LINHA EM UMA TABELA)
# FOREIGN KEY: IMPEDE AÇÕES QUE DESTRUÍRIAM RELAÇÕES ENTRE AS TABELAS
# CHECK: GARANTE QUE TODOS OS VALORES EM UMA COLUNA SATISFAÇAM UMA CONDIÇÃO ESPECÍFICA
# DEFAULT: DEFINE UMA VALOR PADRÃO PARA UMA COLUNA SE NENHUM VALOR É ESPECIFICADO
# CREATE INDEX: USADO PARA CRIAR E RECUPERAR DADOS DO BD MUITO RAPIDAMENTE
# DATE: DATA NO FORMATO YYYY-MM-DD
# TIME(fsp): HORA NO FORMATO HH:MM:SS | fps SIGNIFICA FRACTIONAL SECONDS PRECISION E VAI DE 0 A 6
# DATETIME(fsp): UMA COMBINAÇÃO DE DATA E HORA NO FORMATO YYYY-MM-DD HH:MM:SS | ADICIONE DEFAULT E ON UPDATE PARA PEGAR OS VALORES DE DATA E HORA ATUAIS 
# TIMESTAMP(fsp): VALOR DE TEMPO DESDE ARMAZENADO DESDE A ÉPOCA DO UNIX (1970-01-01 00:00:00 UTC)

create table pessoas(
id int auto_increment primary key, # SÓ PODE HAVER UMA COLUNA COM AUTO INCREMENT E DEVE SER DEFINIDA COMO UMA CHAVE
nome varchar(30) not null,
nascimento date,
sexo enum('M','F'),
peso decimal(5,2), # DOS 5 DÍGITOS 2 FICAM APÓS A VÍRGULA
altura decimal(3,2),
nacionalidade varchar(20) default 'Brasil'
) default charset = utf8; # EVITA PROBLEMAS DE ACENTUAÇÃO

# TAMBÉM PODERIA DEFINIR A PRIMARY KEY NO FINAL DA TABELA
# PRIMARY KEY (id)

describe pessoas;

select * from pessoas;

drop table pessoas;