select * from usuarios;
select * from cursos;

# RELACIONAMENTO 1-PRA-1 A ENTIDADE DOMINANTE GANHA UMA CHAVE ESTRANGEIRA DA OUTRA
# RELCIONAMENTO 1-PRA-MUITOS A ENTIDADE DOS MUITOS GANHA UMA CHAVE ESTRANGEIRA DA OUTRA
# RELACIONAMENTO MUITOS-PRA-MUITOS O RELACIONAMENTO VIRA UMA ENTIDADE COM ATRIBUTOS E N PERTO DELA (COM 1 AFASTADOS)